spring:
  application:
    name: backend
  datasource:
    url: jdbc:mariadb://localhost:3306/clubmontana
    username: root
    password: Luis884994
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 9f86c1001@smtp-brevo.com
    password: ${MAIL_TOKEN}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


security:
  jwt:
    secret: ${SECRET:(2uA,z*8GdN)VfW$5t3(Kl'EQ9|5\`[[U5}v9!~Â£so~>D+A'U}
    expiration-seconds: 900

logging:
  level:
    root: ${LOG:INFO}

storage:
  images:
    base-path: ./data/images
