spring:
  application:
    name: backend
  datasource:
    url: jdbc:mariadb://localhost:3306/clubmontana
    username: root
    password: Luis884994
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  mail:
    host: localhost
    port: 25


security:
  jwt:
    secret: ${SECRET:(2uA,z*8GdN)VfW$5t3(Kl'EQ9|5\`[[U5}v9!~Â£so~>D+A'U}
    expiration-seconds: 900

logging:
  level:
    root: ${LOG:INFO}